// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentFilter struct {
	Author *string `json:"author,omitempty"`
	Body   *string `json:"body,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	Author        string  `json:"author"`
	Body          string  `json:"body"`
	ParentPost    string  `json:"parentPost"`
	ParentComment *string `json:"parentComment,omitempty"`
}

type NewPost struct {
	Author string `json:"author"`
	Body   string `json:"body"`
	Open   bool   `json:"open"`
}

type Query struct {
}

type Subscription struct {
}

type UpdateComment struct {
	Body *string `json:"body,omitempty"`
}

type UpdatePost struct {
	Body *string `json:"body,omitempty"`
	Open *bool   `json:"open,omitempty"`
}
